=== lucasbuttafuoco/TPCampeonato/torneo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT torneo (equipos, arbitros)>
<!ELEMENT equipos (equipo+)> 
<!ELEMENT equipo (nombre, pais, ranking, plantel)> 
<!ELEMENT pais (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT plantel (jugadores, dt+)> 
<!ELEMENT jugadores (jugador+)> 
<!ELEMENT jugador (persona)> 
<!ELEMENT dt (persona, titulosObtenidos)> 
<!ELEMENT arbitros (arbitro*)> 
<!ELEMENT arbitro (persona, aniosReferato)> 
<!ELEMENT persona (tipoDocumento, nroDocumento, nombrex, paisx, fechaNacimiento)> 
<!ELEMENT tipoDocumento (#PCDATA)>
<!ELEMENT nroDocumento (#PCDATA)>
<!ELEMENT nombrex (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT puntuacion (#PCDATA)>
<!ELEMENT paisx (#PCDATA)>
<!ELEMENT aniosReferato (#PCDATA)>
<!ELEMENT titulosObtenidos (#PCDATA)>
<!ELEMENT ranking (#PCDATA)>
<!ATTLIST jugador posicion (arquero | defensor | mediocampista | delantero) #REQUIRED puntuacion (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10) #REQUIRED>

=== lucasbuttafuoco/TPCampeonato/torneo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE torneo SYSTEM "torneo.dtd">
<torneo>
  <equipos>
    <equipo>
      <nombre>Velta de Cigo</nombre>
      <pais>Hispania</pais>
      <ranking>4</ranking>
      <plantel>
        <jugadores>
          <jugador posicion="arquero" puntuacion="8">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>1234</nroDocumento>
              <nombrex>Mangalarga Juan</nombrex>
			        <paisx>Hispania</paisx>
              <fechaNacimiento>30/11/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="arquero"  puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>8564</nroDocumento>
              <nombrex>Noagarrauna Pedro</nombrex>
  			      <paisx>Hispania</paisx>
              <fechaNacimiento>30/03/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="6">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>5678</nroDocumento>
              <nombrex>Quebracho Anibal</nombrex>
			        <paisx>Hispania</paisx>
              <fechaNacimiento>30/11/1995</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="8">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>5678</nroDocumento>
              <nombrex>Nopasaras Daniel</nombrex>
			        <paisx>Hispania</paisx>
              <fechaNacimiento>30/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="7">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>6527</nroDocumento>
              <nombrex>Rompemedias Jose</nombrex>
			        <paisx>Hispania</paisx>
              <fechaNacimiento>01/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="3">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>9687</nroDocumento>
              <nombrex>Lentissimo Massimo</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/11/2005</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>2347</nroDocumento>
              <nombrex>Fortachon Abel</nombrex>
  			      <paisx>Argensur</paisx>			  
              <fechaNacimiento>30/11/2000</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="7">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>9673</nroDocumento>
              <nombrex>Impassable Gino</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>17/02/1996</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="4">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>8791</nroDocumento>
              <nombrex>Immobile Sergei</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>17/05/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>6270</nroDocumento>
              <nombrex>HerMotor Ludwig</nombrex>
  			      <paisx>Germanecia</paisx>
              <fechaNacimiento>31/05/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="8">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>1065</nroDocumento>
              <nombrex>Gambetita Guido</nombrex>
  			      <paisx>Argensur</paisx>
              <fechaNacimiento>31/08/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="5">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>1065</nroDocumento>
              <nombrex>Hachabrava Fernando</nombrex>
  			      <paisx>Argensur</paisx>
              <fechaNacimiento>31/01/1998</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="mediocampista" puntuacion="7">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>6064</nroDocumento>
              <nombrex>Redcard Jimmy</nombrex>
  			      <paisx>Britanilandia</paisx>
              <fechaNacimiento>31/01/1998</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>8084</nroDocumento>
              <nombrex>Laemboca Mutombo</nombrex>
  			      <paisx>Nigembique</paisx>
              <fechaNacimiento>31/03/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="10">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>4235</nroDocumento>
              <nombrex>Tanker Gerrard</nombrex>
  			      <paisx>Germanecia</paisx>
              <fechaNacimiento>31/03/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>3018</nroDocumento>
              <nombrex>Golito Pedro</nombrex>
			        <paisx>Hispania</paisx>
              <fechaNacimiento>01/03/1994</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>3717</nroDocumento>
              <nombrex>Palomito Lucio</nombrex>
  			      <paisx>Hispania</paisx>
              <fechaNacimiento>01/03/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="delantero" puntuacion="9">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>2879</nroDocumento>
              <nombrex>Golentra Ettore</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>01/03/2001</fechaNacimiento>
            </persona>
          </jugador>
        </jugadores>
        <dt>
          <persona>
            <tipoDocumento>DU</tipoDocumento>
            <nroDocumento>9687</nroDocumento>
            <nombrex>Orchestra Luigi</nombrex>
			      <paisx>Italica</paisx>
            <fechaNacimiento>06/06/2005</fechaNacimiento>          
          </persona>
          <titulosObtenidos>15</titulosObtenidos>
        </dt>
      </plantel>
    </equipo>
    <equipo>
      <nombre>Perrissimos</nombre>
      <pais>Italica</pais>
      <ranking>98</ranking>
      <plantel>
        <jugadores>
          <jugador posicion="arquero" puntuacion="3">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>11111</nroDocumento>
              <nombrex>Agujeretti Lino</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/11/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="arquero"  puntuacion="2">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>22222</nroDocumento>
              <nombrex>Sinmanno Renzo</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/03/1985</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>33333</nroDocumento>
              <nombrex>Lastimosso Victor</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/11/1995</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="2">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>44444</nroDocumento>
              <nombrex>Accalambra Dino</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>55555</nroDocumento>
              <nombrex>Nullo Giussepe</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>01/11/1999</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="5">
            <persona>
              <tipoDocumento>PAS</tipoDocumento>
              <nroDocumento>66666</nroDocumento>
              <nombrex>Tragaterra Lucio</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/11/2005</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="4">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
              <nroDocumento>77777</nroDocumento>
              <nombrex>Horripile Genaro</nombrex>
  			      <paisx>Italica</paisx>
              <fechaNacimiento>30/11/2000</fechaNacimiento>
            </persona>
          </jugador>
          <jugador posicion="defensor" puntuacion="3">
            <persona>
              <tipoDocumento>DU</tipoDocumento>
